### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/TREG#6]
You might benefit from checking the LIBD rstats club video on this topic by David Zhang https://youtu.be/ClAin7vTwq0.

You can start with checking the dimensions of the resulting objects, the range of values, types (numeric vs factor etc), or expected error messages (which would verify that you check inputs like from #5).

In general, we'd want to have a high code coverage value, which will make the package look well when we submit it to Bioconductor/etc. Plus for users that check the code coverage badge.

Eventually, whenever we get a bug report, we can adapt those reports and create unit tests from them. 

For creating the test files, use `usethis::use_test()` and use the same name as the `R/*.R` files. This will enable you to use keyboard shortcuts on RStudio to run the companion tests for a given `.R` file.

**Comment by lahuuki** [comment]
At 100% code coverage!
